# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "BPAC-PRD-callbacks-enpoints"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_bucket = "bpac-prd-cognito-callback-bucket"
tags = "Application=callback-app Environment=prd"


parameter_overrides = "Environment=\"prd\" DynamoDBTableName=\"BPAC-PRD-BPPR-ACE-TableCallsInSystem-1RAXWEJQ4WJMI\" HolidayCalendarTableName=\"BPAC-PRD-BPPR-ACE-TableHolidayCalendar-8BONEG9RUGIC\" QueueConfigurationTableName=\"BPAC-PRD-BPPR-ACE-TableQueueConfiguration-V7RRCAXX7HXA\" QueueOperationHoursTableName=\"BPAC-PRD-BPPR-ACE-TableQueueOperationHours-1P3EC19D2UXWZ\" CallbackConcurrencyMetricsTableName=\"BPAC-PRD-CallbackConcurrencyMetrics\" DynamoDBRegion=\"us-east-1\" DynamoDBUri=\"\" CallbackConfigurationParameterName=\"/bppr-amazon-connect-extensions/PRD/callback-configuration\" CognitoUserPoolId=\"us-east-1_tJImiT9rX\" UserAclTableName=\"BPAC-PRD-Callback-UserAcl\" AthenaDatabase=\"bpac-prd-callback-analytics\" AthenaOutputBucket=\"bpac-prd-athena-queries-callback\" AthenaOutputPrefix=\"/\" AthenaTableName=\"calls_in_system_consume\" CallbackReportsTableName=\"BPAC-PRD-CallbackReports\" CallbackReportJobsQueueName=\"BPAC-PRD-CallbackReportJobs\" QueueRegisterStatsTableName=\"BPAC-PRD-Callback-QueueRegisterStats\" QueueGroupInfoTableName=\"BPAC-PRD-queue-group-info-prd\" CorsAllowedOrigin=\"*\" AniBlockedTableName=\"BPAC-PRD-ani-blocked\" ActiveContactsInFlowTableName=\"BPAC-PRD-Callback-ActiveContactsInFlow\" RegistrationIndexTableName=\"BPAC-PRD-Callback-RegistrationIndex\" CallbackLimitAsap=\"120\" CallbackLimitSchedule=\"20\" QueueAssociationTableName=\"BPAC-PRD-BPPR-ACE-TableQueueAssociation-1K0NXHD0SXCEP\" NotAcceptedDetailTableName=\"BPAC-PRD-Callback-NotAcceptedDetail\""
s3_prefix = "callback-endpoints"
region = "us-east-1"
image_repositories = []
stack_name = "BPAC-PRD-callbacks-enpoints"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

#sam deploy --no-resolve-s3 --s3-bucket bpac-prd-callback-bucket --profile bppr-prd-sso --config-file samconfig-prod.toml